# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb5ffa855fa2277c4861bb55eacdea154168c6d8a8ef07a7742280a6dd659c333edfbbe6a3563db5e683ecbe82642c0b7306734d18984fb5ed862ddb4a2534c

test:
  secret_key_base: b5f202c6bf01b9d282daa66dcbff2361281dd3064ad197b9e6e9e4d31c4777b6c848e046f761b79820a711e69535bd69f4c3d643fe8215fe312474062e14c8f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
